name: Build & Publish Backend

on:
  push:
    paths:
      - 'backend/**'

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ghcr.io/8wenders8/fog-yolo-backend:latest

